configProperties:
  version: v2
application:
  helmValues:
    - key: gin-next-2022-06-11t11-36-18-frontend.nocalhost.enabled
      value: true
    - key: gin-next-2022-06-11t11-36-18-backend.nocalhost.enabled
      value: true
